src/main/java/pl/sda/model/Car.java
package pl.sda.model;

import javax.persistence.*;

/**
 * Created by adrian on 01.04.17.
 */
@Entity
@Table(name = "car")
public class Car {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @Column
    private String name;
    @Column
    private String plateNumber;
    @Column
    private String vin;
    @Column
    private Integer mass;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPlateNumber() {
        return plateNumber;
    }

    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }

    public String getVin() {
        return vin;
    }

    public void setVin(String vin) {
        this.vin = vin;
    }

    public Integer getMass() {
        return mass;
    }

    public void setMass(Integer mass) {
        this.mass = mass;
    }
}

src/main/java/pl/sda/model/Customer.java
package pl.sda.model;

import javax.persistence.*;

/**
 * Created by adrian on 31.03.17.
 */
@Entity
@Table(name = "customer")
public class Customer {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column
    private String name;

    @Column
    private String pesel;

    @Column
    private String address;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPesel() {
        return pesel;
    }

    public void setPesel(String pesel) {
        this.pesel = pesel;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
}

src/main/java/pl/sda/model/Purchase.java
package pl.sda.model;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Created by adrian on 31.03.17.
 */
@Entity
@Table(name = "purchase")
public class Purchase {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column
    private Date purchaseTime;

    @OneToOne
    @JoinColumn(name = "car_id")
    private Car purchasedCar;

    @OneToOne
    @JoinColumn(name = "user_id")
    private User seller;

    @OneToOne
    @JoinColumn(name = "customer_id")
    private Customer customer;

    @Column
    private BigDecimal price;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Date getPurchaseTime() {
        return purchaseTime;
    }

    public void setPurchaseTime(Date purchaseTime) {
        this.purchaseTime = purchaseTime;
    }

    public Car getPurchasedCar() {
        return purchasedCar;
    }

    public void setPurchasedCar(Car purchasedCar) {
        this.purchasedCar = purchasedCar;
    }

    public User getSeller() {
        return seller;
    }

    public void setSeller(User seller) {
        this.seller = seller;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}

src/main/java/pl/sda/model/User.java
package pl.sda.model;

import javax.persistence.*;

/**
 * Created by Adrian on 24.03.2017.
 */
@Entity
@Table(name = "user")
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column
    private String name;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

src/main/java/pl/sda/ApplicationController.java
package pl.sda;

import pl.sda.model.Car;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.persistence.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;

/**
 * Managed bean to klasa kontrolera, którą będzie można wywołać w widoku
 * w tym przypadku poprzez #{applicationController}
 * <p>
 * Stan tej klasy bedzie dostępny poprzez cały czas istnienia aplikacji
 */
@ManagedBean(name = "applicationController")
@ApplicationScoped
public class ApplicationController {

    private final EntityManagerFactory emf;
    private final EntityManager em;

    public ApplicationController(){
        emf = Persistence.createEntityManagerFactory("JSFCrudPU");
        em = emf.createEntityManager();
    }

    public EntityManager getEntityManager(){
        return em;
    }

    public List<Car> getList(){
        Query query = em.createQuery("from pl.sda.model.Car c");
        return query.getResultList();
    }

}

src/main/java/pl/sda/controller/ApplicationController.java
package pl.sda.controller;

import pl.sda.model.Car;

import javax.faces.bean.ApplicationScoped;
import javax.faces.bean.ManagedBean;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 * Managed bean to klasa kontrolera, którą będzie można wywołać w widoku
 * w tym przypadku poprzez #{applicationController}
 * <p>
 * Stan tej klasy bedzie dostępny poprzez cały czas istnienia aplikacji
 */
@ManagedBean(name = "applicationController")
@ApplicationScoped
public class ApplicationController {

    private EntityManagerFactory emf;
    private EntityManager em;
    private String data;

    public ApplicationController() {
        emf = Persistence.createEntityManagerFactory("JSFCrudPU");
        em = emf.createEntityManager();
        EntityTransaction transaction = em.getTransaction();
        transaction.begin();
        Car car = new Car();
        car.setMass(1400);
        car.setRegPlate("SK 110KL");
        car.setVin("qwertyuio");
        em.persist(car);
        transaction.commit();
        System.out.println("Baza danych zainicjalizowana");
    }

    public EntityManager getEntityManager() {
        return em;
    }
}

src/main/java/pl/sda/controller/HomeFormController.java
package pl.sda.controller;

import pl.sda.model.Car;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.persistence.EntityManager;
import javax.persistence.EntityTransaction;

/**
 * Created by Adrian on 22.03.2017.
 */
@ManagedBean(name = "form")
@RequestScoped
public class HomeFormController {
    private String name;
    private String regPlate;
    private String vin;
    private Integer totalMass;

    @ManagedProperty(value = "#{applicationController}")
    private ApplicationController applicationController;

    public ApplicationController getApplicationController() {
        return applicationController;
    }

    public void setApplicationController(ApplicationController applicationController) {
        this.applicationController = applicationController;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getRegPlate() {
        return regPlate;
    }

    public void setRegPlate(String regPlate) {
        this.regPlate = regPlate;
    }

    public String getVin() {
        return vin;
    }

    public void setVin(String vin) {
        this.vin = vin;
    }

    public Integer getTotalMass() {
        return totalMass;
    }

    public void setTotalMass(Integer totalMass) {
        this.totalMass = totalMass;
    }

    public void save(){
        this.setName("SET!");

        EntityManager em = applicationController.getEntityManager();

        EntityTransaction transaction = em.getTransaction();

        transaction.begin();
        Car car = new Car();
        car.setMass(this.getTotalMass());
        car.setPlateNumber(this.getRegPlate());
        car.setVin(this.getVin());
        em.persist(car);
        transaction.commit();

        System.out.println("Zapisane do bazy");
    }
}

src/main/java/pl/sda/controller/MenuController.java
package pl.sda.controller;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.persistence.EntityManager;

/**
 * Created by Adrian on 21.03.2017.
 */
@ManagedBean(name = "menuController")
@RequestScoped
public class MenuController {
    /**
     * ta właściwość przeczyta parametr z żądania
     */
    @ManagedProperty(value = "#{param.pageId}")
    private String pageId;

    @ManagedProperty(value = "#{applicationController}")
    private ApplicationController applicationController;

    /**
     * Warunkowa nawigacja pomiędzy stronami
     * @return
     */
    public String showPage() {
        if(pageId == null) {
            return "home";
        }

        if(pageId.equals("1")) {
            return "page1";
        }else if(pageId.equals("2")) {
            return "page2";
        }else {
            return "home";
        }
    }

    public String getPageId() {
        return pageId;
    }

    public void setPageId(String pageId) {
        this.pageId = pageId;
    }

    public ApplicationController getApplicationController() {
        return applicationController;
    }

    public void setApplicationController(ApplicationController applicationController) {
        this.applicationController = applicationController;
    }

    public String getCarList(){
        return "Lista";
    }
}

src/main/webapp/about.xhtml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:f="http://java.sun.com/jsf/core">

<h:body>
    <ui:composition template = "home.xhtml">
        <ui:define name = "header">
            <h2>Page1 header</h2>
        </ui:define>

        <ui:define name = "content">
            <h:dataTable styleClass="table table-striped" value="#{applicationController.list}" var="car">
                <h:column>
                    <f:facet name="header">Name</f:facet>
                    #{car.name}
                </h:column>
                <h:column>
                    <f:facet name="header">Nr rejesracyjny</f:facet>
                    #{car.plateNumber}
                </h:column>
                <h:column>
                    <f:facet name="header">Mass</f:facet>
                    #{car.mass}
                </h:column>
                <h:column>
                    <f:facet name="header">VIN</f:facet>
                    #{car.vin}
                </h:column>
            </h:dataTable>
        </ui:define>

        <ui:define name = "footer">
            <h2>Page1 Footer</h2>
        </ui:define>
    </ui:composition>

</h:body>
</html>

src/main/webapp/contents.xhtml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
    <title>Title</title>
</h:head>
<h:body>
    <ui:composition>
        <div class="starter-template">
            <h:form>
                <div class="row">
                    <div class="col-md-3">
                        nazwa
                    </div>
                    <div class="col-md-3">
                        <h:inputText value="#{form.name}"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        nr rejestracyjny
                    </div>
                    <div class="col-md-3">
                        <h:inputText value="#{form.regPlate}"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        masa
                    </div>
                    <div class="col-md-3">
                        <h:inputText value="#{form.totalMass}"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        vin
                    </div>
                    <div class="col-md-3">
                        <h:inputText value="#{form.vin}"/>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3">
                        zapisz
                    </div>
                    <div class="col-md-3">
                        <h:commandButton action="#{form.save}" value="Zapisz"/>
                    </div>
                </div>
            </h:form>
        </div>
    </ui:composition>
</h:body>
</html>

src/main/webapp/home.xhtml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns = "http://www.w3.org/1999/xhtml"
      xmlns:f = "http://java.sun.com/jsf/core"
      xmlns:h = "http://java.sun.com/jsf/html"
      xmlns:ui = "http://java.sun.com/jsf/facelets">

<h:head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <link rel="icon" href="../../favicon.ico"/>

    <title>Starter Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet"/>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="css/ie10-viewport-bug-workaround.css" rel="stylesheet"/>

    <!-- Custom styles for this template -->
    <link href="css/starter-template.css" rel="stylesheet"/>
</h:head>

<h:body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Project name</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="home.xhtml">Home</a></li>
                    <li><h:outputLink value="about.xhtml">About</h:outputLink></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">

        <ui:insert name = "content" >
            <ui:include src = "contents.xhtml" />
        </ui:insert>


    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script type="text/javascript" src="js/ie10-viewport-bug-workaround.js"></script>
</h:body>
</html>